version: "3.7"
services:
  vscode: # for prettier
    build:
      context: Dockerfile.d/vscode
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    working_dir: /workspace
    volumes:
      - .:/workspace
    user: "${UID:-0}:${GID:-0}"
    command:
      - bash
      - -c
      - |
        cp -f frontend/.eslintrc.json .
        npm install
  frontend:
    build:
      context: Dockerfile.d/frontend.development
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    working_dir: /workspace
    volumes:
      - ./frontend:/workspace
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:3000:3000"
    user: "${UID:-0}:${GID:-0}"
    command:
      - bash
      - -c
      - |
        npm install
        npm run dev
