[config]
skip_core_tasks = true
min_version = "0.26.0"

[tasks.prepare]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../"

[tasks.frontend]
alias="build-frontend"

[tasks.build-frontend]
dependencies = [
  "prepare"
]
script = [
'''
rm -rf Dockerfile.d/frontend/rootfs
mkdir -p Dockerfile.d/frontend/rootfs/
cp -Rp frontend Dockerfile.d/frontend/rootfs/workspace
docker build --no-cache --target production Dockerfile.d/frontend
'''
]

[tasks.default]
dependencies = [
  "build-frontend"
]
